### ISSUE TITLE
superfluous var define

### ISSUE THREAD

**Issue by espretto** [jrburke/amdefine#28]
how about a build pragma to exclude it?
```js
//>>excludeStart('amdefine', true);
if (typeof define !== 'function') { var define = require('amdefine')(module) }
//>>excludeEnd('amdefine');
```

**Comment by jrburke** [comment]
The r.js optimizer will [remove the amdefine block by default](https://github.com/jrburke/r.js/blob/master/build/example.build.js#L626), so I do not think this is needed. Will close for now, but feel free to continue discussion and we can reopen later if needed.
