### ISSUE TITLE
Named module support

### ISSUE THREAD

**Issue by jonkessler** [jrburke/amdefine#31]
Is amdefine intended to work with named AMD modules? It seems to work perfectly with anonymous modules, but if I name my modules, instead of getting the module when I `require` it, I get `undefined`. Any suggestions?

**Comment by jrburke** [comment]
It is not designed for named modules, only anonymous modules. It supports a named module concept for multiple modules defined in a particular file, but those modules are not visible outside of the current file. It is only useful for a particular kind of build case.

For using a module by outside modules, stick with anonymous modules.

Closing as a discussion ticket, but feel free to continue discussion here.

**Comment by jonkessler** [comment]
All right, thanks for the quick response!
