### ISSUE TITLE
not compatible with jQuery > 3.0.0

### ISSUE THREAD

**Issue by VicFrolov** [jrburke/amdefine#32]
Hey, I could be wrong but apparently jquery no longer allows .load(), and it must be .on('load', function()...), I think webpack uses amdefine as a dependency, was wondering if there is some sort of workaround, or if I must use an older version of jQuery?

**Comment by jrburke** [comment]
I am not sure how this relates to amdefine? It is not needed for jQuery, it has a UMD block for registering with different module systems. Going to close for now, since I think this may have been filed in the wrong repo, but if more information is added we can easily reopen it.
